### ISSUE TITLE
Sidebar glitch

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Cordova#57]
As pointed by @infinitnet in https://github.com/RocketChat/Rocket.Chat.Android.Lily/issues/15

The icons on the right sidebar randomly disappear. If I kill and restart the app or switch rooms a few times the icons are come back. Issue appear to happen randomly. Using latest release from Play Store on a Sense 7 ROM, Android 5.0.2.
![screenshot_2016-01-06-17-43-24](https://cloud.githubusercontent.com/assets/6189915/12151343/fc06f184-b4ae-11e5-8817-c79e097de836.png)

**Comment by sampaiodiego** [comment]
@infinitnet what server version are you using? I think this glitch was solved by https://github.com/RocketChat/Rocket.Chat/pull/1782 which is not in v0.12

**Comment by infinitnet** [comment]
I see, I assumed it were related to the app. I'm running an older version (the .tar from your S3 which is more than a week old, so doesn't include the commit you mentioned). You can close this then and I guess I'll have to wait until the tarball on the S3 is updated. Apologies about the inconvenience.

**Comment by sampaiodiego** [comment]
no problem, really! :smiley: 
it's really important to us when the community get involved :wink: 
I'll close then.. thank you

**Comment by dytec** [comment]
This issue still happens to me.
Server version 0.19, Nexus 5 with Android 6.0.1
If you switch 2 channels and then go back 1 channel the icons are added back to the sidebar.

**Comment by pschonder** [comment]
Happens to me too on iOS & Android.

I think this is related to https://github.com/RocketChat/Rocket.Chat.Cordova/issues/15

**Comment by pschonder** [comment]
@dytec can you test it on your android-device? i only have a simulator to test with.

**Comment by geekgonecrazy** [comment]
Yes lets refer to #15 the issue still happens.
